[tool.poetry]
name = "oca-addons-repo-template"
version = "0.0.0" # Just a placeholder; the real version is the git tag
description = "Template for OCA addon repos"
authors = ["Odoo Community Association (OCA)"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6.2"
copier = "^5.1.0"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
pre-commit = "^2.15.0"
pytest-xdist = "^2.4.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
